name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Pages
          uses: actions/configure-pages@v3

        - name: Reby setup
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.2' # Not needed with a .ruby-version file
            bundler-cache: true
        - name: Install Jekyll
          run: gem install jekyll
        - name: Build with Jekyll
          run: jekyll build --source ./ --destination ./_site

        # # Copy nojekyll to bypass understore folder and file
        # - name: Modify _site directory permissions
        #   run: sudo chmod -R 777 ./_site
        # - name: Copy .nojekyll file
        #   run: cp .nojekyll ./_site/
        # - name: List files
        #   run: ls -la ./_site 

        # Upload artifacts to be downlowed in the deployment step
        - name: Upload production-ready build files
          uses: actions/upload-artifact@v2
          with:
            name: production-files
            path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build

    steps:
        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
            name: production-files
            path: ./_site

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./_site
            cname: www.tagiml.com

