name: Deploy

on:
  push:
    branches:
      - main

# # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#     contents: read
#     pages: write
#     id-token: write
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup Pages
          uses: actions/configure-pages@v3
        - name: Build with Jekyll
          uses: actions/jekyll-build-pages@v1
          with:
            source: ./
            destination: ./_site
        # - name: Upload artifact
        #   uses: actions/upload-pages-artifact@v2
        - name: Upload production-ready build files
          uses: actions/upload-artifact@v2
          with:
            name: production-files
            path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build

    steps:
        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
            name: production-files
            path: ./_site
  
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./_site

    # steps:
    #   - name: Deploy to GitHub Pages
    #     id: deployment
    #     uses: actions/deploy-pages@v2
    #       # cname: www.hazone.me  # Uncomment this line if you want to use a custom domain
